serverProto: "http://"
serverHost:  "localhost:3000"
localHost:   "localhost:3000"
dataDir:     "./data"
settingsFile: "settings.yml"
fromName:    "Git Notify"
fromEmail:   "hub@gitnotify.com"
githubURLEndPoint: "https://github.com/"
githubAPIEndPoint: "https://api.github.com/"
smtpHost:          "email-smtp.us-east-1.amazonaws.com"
