# Required to start the server
serverProto: "http://"
serverHost:  "localhost:3000"
localHost:   "localhost:3000"

# Authentication Options
githubURLEndPoint: "https://github.com/" # "https://github.acme.com/"
githubAPIEndPoint: "https://api.github.com/" # "https://github.acme.com/api/v3/"

gitlabURLEndPoint: "https://gitlab.com/" # "https://gitlab.acme.com/"
gitlabAPIEndPoint: "https://gitlab.com/api/v3/" # "https://gitlab.acme.com/api/v3/"

# Location of data being saved
dataDir:     "./data"
settingsFile: "settings.yml"

# Notification From Name
fromName:    "Git Notify"

# Email Setup
fromEmail:   "hub@gitnotify.com"
smtpHost:    "email-smtp.us-east-1.amazonaws.com"
# smtpHost:    "" # set as "" to disable emails
smtpPort:    587
sesConfigurationSet: "gitnotify"

googleAnalytics: ""
runMode: "dev" # "prod"
webhookIntegrations: ["slack"] # generic
templateDir: "tmpl/" # should end with a /
templatePartialsDir: "tmpl/partials/" # should end with a /

cacheIncomingRequests: true
sentryDSN: ""
